NUM_AGENTS: int = 30
MAX_SPEED: int = 50
NEIGHBOUR_RADIUS: int = 50
AGENT_RADIUS: int = 5

SCREEN_WIDTH: int = 1080
SCREEN_HEIGHT: int = 720
DT: float = 0.02

AGENT_COLOR: str = "#808F85"
WINDOW_COLOR: str = "#DCE0D9"
WIND_ARROW_COLOR = "#FFFFFF"
OBSTACLE_COLOR: str = "#31081F"
WIND_FORCE_TEXT_COLOR: str = "#FFFFFF"

MIN_RANDOM_VEL: int = -5
MAX_RANDOM_VEL: int = 5

CIRCLE_OBSTACLE_RADIUS: int = 30
CIRCLE_DISTANCE: int = 70 
REPULSION_STRENGTH: float = 40

WIND_FORCE_STRENGTH: float = 2.5
WIND_ARROW_LENGTH = 70
WIND_ARROW_HEAD_SIZE = 10